- name: Ensure cache is up to date
  apt:
    update_cache: yes
- name: Install packages
  apt:
    name:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: postgresql
    state: started
    enabled: true
- name: Configure host based authentication.
  template:
    src: templates/pg_hba.conf.j2
    dest: /etc/postgresql/10/main/pg_hba.conf
    mode: 0600
  notify: restart postgresql
  become: true
- name: Configure listen bnetworks.
  copy:
    src: files/postgresql.conf
    dest: /etc/postgresql/10/main/postgresql.conf
    mode: 0600
  notify: restart postgresql
  become: true
- name: Ensure PostgreSQL databases are present.
  postgresql_db:
    name: '{{ db_name }}'
  become: true
  become_user: postgres
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true
- name: Ensure PostgreSQL users are present.
  postgresql_user:
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    state: present
    db: '{{ db_name }}'
    priv: "ALL"
    encrypted: true
  become: true
  become_user: postgres
  notify: restart postgresql
  vars:
    ansible_ssh_pipelining: true