  - name: "Instala nodejs, npm e git"
    apt:
      name: 
        - nodejs
        - npm
        - git
        - unzip
      update_cache: yes
    become: yes
  - name: "Download app from s3 bucket"
    shell: |
      aws s3 cp s3://allanfvc/files/app.zip app.zip
    args:
      chdir: /tmp/
    become: yes
  - name: "Unzip app"
    shell:  rm -rf app/ && unzip app.zip -d app
    args:
      chdir: /tmp/
    become: yes
  - name: Install pm2
    npm: name=pm2 global=yes production=yes
  - name: "Install app dependencies"
    npm:
      path: /tmp/app/
      state: present
    become: yes
  - name: "Start app"
    shell: | 
      cd /tmp/app 
      export DATABASE_URL=postgres://{{ db_user }}:{{ db_password }}@{{ db_ip_addr }}:5432/{{ db_name }} 
      pm2 -f start index.js --name app
    become: yes
